### ISSUE TITLE
[storage] Use enum for storage type

### ISSUE THREAD

**Issue by bausano** [exteranto/framework#80]
It would be better if the `Storage` constructor took an `enum` instead of `string`.

**Comment by kouks** [comment]
This should be reconsidered altogether. If we want to introduce `MemoryStorage`, enum is out of the question because we can't merge the memory implementation in one class with the other ones. We would have to define a separate implementation for `LocalStorage`, `SyncStorage` and `MemoryStorage`.

This, however, requires some improvements in the IOC container which I have planned to look at in March after I am less busy.

**Comment by kouks** [comment]
Closed by #110
