### ISSUE TITLE
[global] Merge Some Packages Into One NPM

### ISSUE THREAD

**Issue by bausano** [exteranto/framework#9]
In order to make the CI CD and contributing easier, I would merge following packages into one GitHub and NPM repository:

The _core_ package should welcome _events_, _IOC_, _support_ (all stated as it's dependencies), and potentially _exceptions_ and _compatibility_. I reckon all other packages should stay as they are.

1. events - exports are distinct enough
2. IOC - exports are distinct enough
3. support - for now, exports are distinct enough
4. exceptions? - we would have to come up with some namespacing if wanted to do include it in the refactor. I would rather include them than not.
5. compatibility? - exports are in my opinion not distinct enough, but still would work and is less work than exceptions. I would rather not include it, but I am not strongly against it.

I think that if we merge these packages, we can say:
"Exteranto is in the version of x.x.x" without having to update all other packages to this version. Since modules like messaging, storage, ... are more like extensions to the core anyway. Like vue and vue-router.

**Comment by kouks** [comment]
Merged all GitHub repos into one and improved the CI pipelines (closes #11 ) so that:
- all exteranto dependencies are now in `file:../x` format
- upon release, all these local dependencies are bulk replaced with the appropriate tag version

Before collapsing npm packages, I would give this a go and see how it works.
